name: mfbocd
channels:
  - defaults
dependencies:
  - appnope=0.1.2=py37hecd8cb5_1001
  - argon2-cffi=20.1.0=py37h9ed2024_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - ca-certificates=2021.1.19=hecd8cb5_1
  - certifi=2020.12.5=py37hecd8cb5_0
  - cffi=1.14.5=py37h2125817_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=h18a8e69_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - expat=2.2.10=hb1e8313_2
  - freetype=2.10.4=ha233b18_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.67.4=hdf23fa2_1
  - icu=58.2=h0a44026_3
  - importlib-metadata=3.7.3=py37hecd8cb5_1
  - importlib_metadata=3.7.3=hd3eb1b0_1
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.21.0=py37h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.2=py37hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.3.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py37h23ab428_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.2.0=h87d7836_0
  - libwebp-base=1.2.0=h9ed2024_0
  - lz4-c=1.9.3=h23ab428_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.3.4=py37hecd8cb5_0
  - matplotlib-base=3.3.4=py37h8b3ea08_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37ha059aab_0
  - mkl_random=1.1.1=py37h959d312_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.3.0=py37hecd8cb5_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - olefile=0.46=py37_0
  - openssl=1.1.1j=h9ed2024_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.12=hecd8cb5_0
  - pandocfilters=1.4.3=py37hecd8cb5_1
  - parso=0.7.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py37h5270095_0
  - pip=21.0.1=py37hecd8cb5_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.17.3=py37haf1e3a3_0
  - python=3.7.10=h88f2d9e_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py37h23ab428_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - readline=8.1=h9ed2024_0
  - scipy=1.6.1=py37h2515648_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37hecd8cb5_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.15.0=py37hecd8cb5_0
  - sqlite=3.35.2=hce871da_0
  - terminado=0.9.3=py37hecd8cb5_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h9ed2024_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
